[metadata]
name = SaidouModule
version = 1.3.0
author = Meddahi Saïd
author_email = s.meddahi.fo@gmail.com
description = Module contenant des outils de réseaux de neurones simples et de manipulation d'images pixelisées.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/SMedd69/SaidouModule
classifiers =
    Development Status :: 4 - Beta
    License :: OSI Approved :: MIT License
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8

[options]
packages = find:
python_requires = >=3.7
install_requires =
    numpy
    matplotlib
    opencv-python
    tqdm
    scikit-learn

[options.packages.find]
exclude =
    tests
    docs
